name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: mkdir -p ~/translator-dssat-artifacts
    - run: echo "java -jar quadui-1.3.8-hf4.jar \"\$@\"" > ~/translator-dssat-artifact/run.sh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
           cp target/translator-dssat-1.2.20-jar-with-dependencies.jar ~/translator-dssat-artifacts/translator-dssat-1.2.20-jar-with-dependencies.jar
    - uses: actions/upload-artifact@master
      with:
        name: translator-dssat-1.2.20-artifact
        path: ~/translator-dssat-artifacts
